### ISSUE TITLE
Specs satisfying the `StripeFinancialConnections (= 22.5.1, ~> 22.5.1), StripeFinancialConnections (~> 22.7.0)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by anija** [stripe/stripe-react-native#1103]
I'm trying to upgrade to latest version, but when I launch pod install i got
```
Specs satisfying the `StripeFinancialConnections (= 22.5.1, ~> 22.5.1), StripeFinancialConnections (~> 22.7.0)` dependency were found, but they required a higher minimum deployment target.
```

My minimun deployment target is 12.4 and should be enough, accordin to the documentation.

`platform :ios, '12.4'`

**Comment by charliecruzan-stripe** [comment]
This is probably an Xcode caching issue, try cleaning your build folder in Xcode: 
<img width="264" alt="Screen Shot 2022-08-25 at 1 55 13 PM" src="https://user-images.githubusercontent.com/97612659/186767100-1fc8dc6f-4377-4715-9388-0dea9edc7e18.png">
 
and maybe even clearing the `~/Library/Developer/Xcode/DerivedData/` folder.

This issue might be semi relevant : https://github.com/stripe/stripe-react-native/issues/970

Closing since this isn't a bug with the SDK and is specific to your local project, but lmk if there's more I can do to help :)
