### ISSUE TITLE
Question: Why does expo use outdated version?

### ISSUE THREAD

**Issue by alxndr777** [stripe/stripe-react-native#1161]
Hi, I think this is a dummy question, but can't really find an answer to my question.

I currently use expo version 6.0.6, which I believe is the latest one.
I ran expo install @stripe/stripe-react-native, and I got 0.2.3 installed.
I think each version of the Expo SDK comes with a version of stripe bundled inside. Version 44 (which I have) comes with 0.2.3 has a LOT of bugs that were already fixed in this repo. So how can I use the updated version of this library with no bugs for expo? What should I do?

Thank you.

**Comment by charliecruzan-stripe** [comment]
Expo's latest version is SDK 46, which uses 0.13.1: https://github.com/expo/expo/blob/sdk-46/packages/expo/bundledNativeModules.json#L12

However, if you use the bare workflow instead of the managed workflow, you can use the most recent versions of this library (this means you can't use the Expo Go client for development, though)

**Comment by Pcummings** [comment]
@alxndr777 I am on sdk 46, managed, and had issues building as expo pushed 0.13.0 I manually upgraded to the latest version of stripe-react-native and it works like a charm.
