### ISSUE TITLE
canAddCardToWallet returns empty details when primaryAccountIdentifier is null on iOS

### ISSUE THREAD

**Issue by kathrynnlester** [stripe/stripe-react-native#1339]
**Describe the bug**

In versions 0.25.0 and 0.26.0 `canAddCardToWallet` returns empty `details` when `primaryAccountIdentifier` is `null` on iOS. As a result, we are unable to tell if the card is in the device's wallet. 

**To Reproduce**
1. Call `canAddCardToWallet` with null as `primaryAccountIdentifier` and last four digits of a card in the iOS device's wallet. 
2. As a result, `details` does not contain the appropriate status.

**Expected behavior**
We expect that `canAddCardToWallet` can accept `null` for `primaryAccountIdentifier`, and that details contains `{ status: 'CARD_ALREADY_EXISTS' }` for a card in the virtual wallet.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro, iPhone 7 Plus, iPhone 14 Pro Max
 - OS: iOS
 - Version: 16.3, 16.0.3, 15.7.3

**Comment by charliecruzan-stripe** [comment]
hi! `primaryAccountIdentifier` should be the value you are getting for [`card.wallets.primary_account_identifier`](https://stripe.com/docs/api/issuing/cards/object#issuing_card_object-wallets-primary_account_identifier) from your server. Are you receiving back an empty string or null for that value?

**Comment by kathrynnlester** [comment]
Hi, this works for us for users with a card— thank you for the suggestion! 

Can we still rely on the `details` object to check if a device is supported (`status` is "UNSUPPORTED_DEVICE")? We use this before creating a card, so we do not have access to `card.wallets.primary_account_identifier` at that point.

**Comment by charliecruzan-stripe** [comment]
You can rely on the status `UNSUPPORTED_DEVICE` even when you do not pass the `primaryAccountIdentifier`, since device-level support is independent of the card being added. 

However, you **cannot** rely on the `canAddCard` boolean result, since without the `primaryAccountIdentifier`, we are not able to accurately tell whether the device has already provisioned that card. 

Let me know if that answers your question @kathrynnlester ! happy to go into more detail if necessary

**Comment by kathrynnlester** [comment]
@charliecruzan-stripe Yes, that answers my question. Thank you so much!
