### ISSUE TITLE
textColor prop not working

### ISSUE THREAD

**Issue by savancodexive** [stripe/stripe-react-native#1359]
### textColor and  placeholderColor prop not working for ios

**I am using the background color white and the theme white Appearance.
it's working fine in white Appearance because the text's default color is black.
but When I use a black Appearance then text's default color is white. so the text is not showing up.
I tried to change black color by give props but it's not working**

`"react": "18.1.0",`
`"react-native": "0.70.6",`
`"@stripe/stripe-react-native": "^0.26.0",`

**Screenshots**
![image](https://user-images.githubusercontent.com/85383682/232413786-93250e94-b816-4133-b057-2ec82e229e7c.png)
![image](https://user-images.githubusercontent.com/85383682/232412809-9353d114-b833-4a6e-be9a-33712651849b.png)

**Smartphone (please complete the following information):**
All Device

**Comment by charliecruzan-stripe** [comment]
Hi! This is because a lot of CardForm's `cardStyle` properties are Android-only- https://stripe.dev/stripe-react-native/api-reference/interfaces/CardFormProps.html#cardStyle

I would recommend using `CardField` if you're looking for a lot of customization options. Or the Payment Sheet. If you use `CardForm`, you'll have to make use of the `backgroundColor` setting I think.
