### ISSUE TITLE
Customize UI for CardField and CardForm

### ISSUE THREAD

**Issue by neilanthonyte** [stripe/stripe-react-native#1389]
Hi, how do I make the UI looks like this? What component should I use?

<img width="307" alt="Screen Shot 2023-05-12 at 12 06 52 PM" src="https://github.com/stripe/stripe-react-native/assets/99723639/fe9fd2b3-fbf8-4c86-87ad-a6f4b5912ccb">

The UI/style inside the CardField and CardForm component is limited and sometimes it does not work i.e CardForm border color.

"@stripe/stripe-react-native": "0.19.0"
"react-native": "0.70.6"

**Comment by charliecruzan-stripe** [comment]
Hi! CardField offers a lot more customization than CardForm, so I recommend that option. You can use the `cardStyle` and `placeholders` props for that.

As for injecting values, you can't do that (and likely don't want to, but that's up to you) because of [PCI concerns](https://stripe.com/guides/pci-compliance). If you directly handle card data, things get quite a bit more complex. That's up to you, though, depending on what your needs are.

**Comment by santiseijas** [comment]
hi @neilanthonyte,
Were you able to make the inputs customizable?
Thanks
