### ISSUE TITLE
Google Pay error [OR_BIBED_07] in production and working fine in Development 

### ISSUE THREAD

**Issue by Psutariya** [stripe/stripe-react-native#1433]
**Describe the bug**
we use google pay useing stripe but in development working  fine but in production throw some error  like ****this live merchant is having trouble accepting your payment right now by using different payment method OR_BIBED_0**7**.this error show in react native so plz help me solve this error.

**To Reproduce**
1.Click on 'Google Pay button'

**Expected behavior**
add the card after that this card show and If we select the card after that payment success.

Desktop :
OS:[ANDROID]
Browser [chrome]

**Smartphone (please complete the following information):**
 Device: [Android:oppo f9 pro]
OS: [10]
Browser [estock browseri]
Version [10]
![WhatsApp Image 2023-06-26 at 5 44 00 PM](https://github.com/stripe/stripe-react-native/assets/104578057/50643b14-bcad-40f7-bc5f-259868f77065)

**Comment by seanzhang-stripe** [comment]
This error usually happens when you just switch the environment from Test to Production. 

You can refer to this [going live](https://stripe.com/docs/google-pay?platform=android#going-live) guide and follow [Google’s instructions](https://developers.google.com/pay/api/android/guides/test-and-deploy/request-prod-access) to request for production access.
