### ISSUE TITLE
Question about making subscription payment using payment sheet- so that it can accept the card details and allow payment and at the same time save payment details for future use.

### ISSUE THREAD

**Issue by pcatjee** [stripe/stripe-react-native#1444]
Hello, 

I am trying to create a subscription paymentsheet in react native, below is my code. When I uncomment **trial_period_days: 3**, then it works even if payment methods are not declared. But if I comment this line, then I am getting error - **"StripeInvalidRequestError: This customer has no attached payment source or default payment method. Please consider adding a default payment method."** I tried below code to declare payment methods, but it did not work. I want new customers to also be able make payments and save their card information at same checkout time on the payment sheet.

const stripe = require('stripe')(stripeSecretKey);
const express = require('express');
const bodyParser = require('body-parser');
const app = express();

app.use(bodyParser.json());
app.get('/', (req, res) => {
  res.send('Test');
});
app.post('/payment-sheet-subscription', async (req, res) => {
  const {email = `test${Math.floor(Math.random() * 9999) + 1}@domain.com`} =
    req.body;

  const customer = await stripe.customers.create({email});

  const ephemeralKey = await stripe.ephemeralKeys.create(
    {customer: customer.id},
    {apiVersion: '2020-08-27'},
  );
  const PRICE_ID = 'price_1NQ4EnSBro6pGrG8ZYfdBX5x';
  const subscription = await stripe.subscriptions.create({
    customer: customer.id,
    items: [{price: PRICE_ID}],
    // trial_period_days: 3,
  });
  const updatedSubscription = await stripe.subscriptions.update(
    subscription.id,
    {
      payment_settings: {
        payment_method_types: ['card'],
      },
    },
  );
  if (typeof updatedSubscription.pending_setup_intent === 'string') {
    const setupIntent = await stripe.setupIntents.retrieve(
      updatedSubscription.pending_setup_intent,
    );

    // if (typeof subscription.pending_setup_intent === 'string') {
    //   const setupIntent = await stripe.setupIntents.retrieve(
    //     subscription.pending_setup_intent,
    //   );

    return res.json({
      setupIntent: setupIntent.client_secret,
      ephemeralKey: ephemeralKey.secret,
      customer: customer.id,
    });
  } else {
    throw new Error(
      'Expected response type string, but received: ' +
        typeof subscription.pending_setup_intent,
    );
  }
});

**Comment by seanzhang-stripe** [comment]
When you remove `trial_period_days`, the first invoice that the subscription creates would require payment, and that's why you need to set a payment_method during Subscription creation. 

If a payment_method is not available during subscription creation, you can set [payment_behavior](https://stripe.com/docs/api/subscriptions/create?lang=node#create_subscription-payment_behavior) to `default_incomplete`.  Remember to set [save_default_payment_method](https://stripe.com/docs/api/subscriptions/create?lang=node#create_subscription-payment_settings-save_default_payment_method) to `on_subscription` so that Stripe would use the payment_method paid in the first invoice as the default payment method for the subscription. 

Once the subscription is created, send its first invoice's `payment_intent_client_secret` to your react native app and launch PaymentSheet. Although there's no dedicated subscription integration document for mobile, the flow is similar to web elements, which you can find it [here](https://stripe.com/docs/billing/subscriptions/build-subscriptions?ui=elements#create-subscription
)
