### ISSUE TITLE
Payment sheet not showing on iOS 17.1.1+

### ISSUE THREAD

**Issue by the-habu** [stripe/stripe-react-native#1581]
**Describe the bug**
Tested with iOS 17.0, 17.1.1 and 17.2

Starting with iOS 17.1.1 (iOS 17.0 works), the stripe payment sheet will be invisible but still touchable.
The screen darkens as if it would want to show an overlay sheet. Also when saving and working dev mode, sometimes the sheet does appear for a second, until the app cold-refreshes and goes back to the main screen (our fast refresh setup broken).

I see no problems in the RN and native logs. Seeing the sheet pop up on refresh, leads me to believe that this is a rendering problem.

**To Reproduce**
- Use iOS 17.2 simulator (I could only get 17.0 and 17.2)
- Try to show payment sheet via hook.
- Screen darkens, payment not showing.
- Pressing in the bottom area opens e.g. country selector. 

**Expected behavior**
Payment sheet shows as normal.

**Smartphone**
 - Device: iPhone or Simulator 
 - OS: iOS 17.1.1+
 - RN Version: 0.64.2 (aware of the outdatedness and your 0.69.9 dev dependency)
 - Stripe SDK: 0.35.0

**Comment by the-habu** [comment]
Seems to be related to XCode versions. I will give an update on this ticket, if I have a better analysis.

**Comment by erfan93na** [comment]
Did you find any solution?

**Comment by the-habu** [comment]
> Did you find any solution?

Yes, we found out it is related to XCode 15 while XCode 14 works perfectly. 
I am not even sure yet if it is happening with current version of this lib, as we haven't managed to upgrade yet.

**Comment by mahendraios** [comment]
I'm seeing this issue with @stripe/stripe-react-native : 0.37.0 and Xcode 15.0.

**Comment by vineetsansare** [comment]
@the-habu : 

I am facing the same issue with one of my client's apps.
I know this issue is marked closed. But is there any workaround or concrete solution that works for **XCode 15.3** and iOS **17.4.1**

![Simulator Screenshot - iPhone 15 Plus - 2024-05-28 at 23 48 27](https://github.com/stripe/stripe-react-native/assets/6418402/81f03060-fca0-46f8-9e06-75ffb821dafb)
![Simulator Screenshot - iPhone 15 Plus - 2024-05-28 at 23 48 34](https://github.com/stripe/stripe-react-native/assets/6418402/226e5535-678c-4ec3-9ce0-621d93efaf32)
![Simulator Screenshot - iPhone 15 Plus - 2024-05-28 at 23 48 41](https://github.com/stripe/stripe-react-native/assets/6418402/700356d6-6f0c-41f0-a07d-4cb109f594b6)
