### ISSUE TITLE
iOS. Processing is taking too long if a user closes the Amazon payment page

### ISSUE THREAD

**Issue by aleks-khomenko** [stripe/stripe-react-native#1792]
**Describe the bug**
After rn-stripe update from 0.35.0 to 0.40.0 I noticed that processing is taking too long if the user closes the Amazon payment page (see video). As for 0.35.0 version it works fine (see video)

**To Reproduce**
1. presentPaymentSheet
2. Click on Amzaon
3. Proceed to the Amazon payment page
4. Tap the Close button to close the page

**Actual behavior**
Processing is taking too long if a user closes the Amazon payment page

**Expected behavior**
Processing stops after a user closes the Amazon payment page.

**Video**
rn-stripe v. 0.40.0

https://github.com/user-attachments/assets/af59f0af-01f5-4f88-9f9b-dbbf0854d74f

rn-stripe v. 0.35.0

https://github.com/user-attachments/assets/6fd5a3df-3312-481c-94eb-cf05a3bf675d

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11 Pro Max]
 - OS: [e.g. iOS 18.1.1]

**Additional context**

**Comment by porter-stripe** [comment]
Hi @aleks-khomenko thanks for opening this! This is unfortunately expected behavior for now. The payment should cancel out after about 10-15 seconds. We are looking into improving this, but there is nothing on our roadmap in the near term. Going to close this out and will post an update here if anything changes.
