### ISSUE TITLE
onChangeCard is not working with react native 0.76 newArc

### ISSUE THREAD

**Issue by eman747** [stripe/stripe-react-native#1801]
"@stripe/stripe-react-native": "^0.40.0",
<CardField
      postalCodeEnabled={false}
      dangerouslyGetFullCardDetails={true}
      placeholders={{number: '4242 4242 4242 4242'}}
      cardStyle={styles.cardStyle}
      style={styles.fieldStyle}
      onCardChange={cardDetails => setCardDetails(cardDetails)}
    />
if i console cardDetails nothing prints. Please provide a fix it for both android and IOS
IOS crashed on cardfield newArch

**Comment by justynpollard1** [comment]
I'd suggest moving to using the new CustomerSheet Element or the PaymentElementSheet. There seems to be a number of issues with CardField with the new Arch and its a legacy component now so not sure if the the Stripe team will be fixing these issues or not.

**Comment by haris18896** [comment]
use `newArchEnabled=false` in the **android/gradle.properties** to disable the newArch then it will work

**Comment by samer-stripe** [comment]
Hi everyone! I'm sorry it's taken us way so long to support the new architecture. We recently fixed compatbility with the new architecture in the latest React Native version (0.43.0). 

I apologize again for the delay. Please keep the feedback coming as well; we will do a better job at communicating with you! Closing this for now but feel free to re-open if this issue is still going on.
