### ISSUE TITLE
Add `createToken` method

### ISSUE THREAD

**Issue by talkshoplivedev** [stripe/stripe-react-native#187]
Our backend workflow relies heavily on client-side sending card tokens (e.g. `tok_`). Is this possible to achieve with this package? If not, we would really appreciate any guidance on how we can make this package work for us given our current workflow posture.

**Comment by thorsten-stripe** [comment]
Okay, we'll look into adding a `createToken` method.

* iOS: https://stripe.dev/stripe-ios/docs/Classes/STPAPIClient.html#/c:@CM@Stripe@objc(cs)STPAPIClient(im)createTokenWithPayment:completion:

* Android: https://stripe.dev/stripe-android/stripe/com.stripe.android/create-card-token.html

**Comment by talkshoplivedev** [comment]
Thanks so much @thorsten-stripe

**Comment by pinpointpanda** [comment]
Very pleased to find this thread! For our app, we will absolutely be migrating to the PaymentIntents workflow, but not quite yet - so a short-term solution that allows our FE to generate the card token would be great for us. Then our RN app can work with this library instead of our current WebView punchout for `stripe.js` and we'll be ready to move forwards with the more holistic workflow more quickly.
