### ISSUE TITLE
Prebuilt UI multi step

### ISSUE THREAD

**Issue by vxgnesh** [stripe/stripe-react-native#270]
I need more info on this specific code. It is located in the Server.js file. So the api call /payment-sheet is used by the Prebuilt UI Custom Screen. In this how do we specify or pass the customer. Here it takes the latest one but how do we pass a customer other than the latest one/customers.data[0]? 

Is there any documents i could look into to get a better sense of what's going on in this code? 

**Server side**:
> `
app.post('/payment-sheet', async (_, res) => {  
  const { secret_key } = getKeys();
  const stripe = new Stripe(secret_key as string, {    
      apiVersion: '2020-08-27',    
     typescript: true,   
   });

  const customers = await stripe.customers.list();

  // Here, we're getting latest customer only for example purposes.  

   const customer = customers.data[0];

  if (!customer)  {    
     res.send({     
         error: 'You have no customer created',   
     });  }
  const ephemeralKey = await stripe.ephemeralKeys.create(    
      { customer: customer.id },    
     { apiVersion: '2020-08-27' }  
    );  
const paymentIntent = await stripe.paymentIntents.create({   
   amount: 1099,    
   currency: 'usd',    
   customer: customer.id, 
 }); 
 res.json({   
  paymentIntent: paymentIntent.client_secret,    
  ephemeralKey: ephemeralKey.secret,  
  customer: customer.id,  
});
});`

**Client Side**

`const fetchPaymentSheetParams = async () => {
    const response = await fetch(`${API_URL}/payment-sheet`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    const { paymentIntent, ephemeralKey, customer } = await response.json();

    return {
      paymentIntent,
      ephemeralKey,
      customer,
    };
};`

**Comment by thorsten-stripe** [comment]
You will need to provide the customer ID for your authenticated user. In our example we do not handle authentication, that's why we simply feed in the latest customer object, but that's only for demo purposes. In your application you will need to make sure the customer is authenticated. 

You can see an example with Firebase Auth being used here: https://github.com/stripe-samples/firebase-mobile-payments/tree/main/ios-swiftui

If you don't authenticate users in your app, you can just omit `customerId` and `customerEphemeralKeySecret` params which just means that the payment sheet won't save the card details to a customer object, so every time your customer pays they would have to reenter their payment details.
