### ISSUE TITLE
[Question] - Is stripe allowed to take payments on Mobile app (without google or apple pay)

### ISSUE THREAD

**Issue by sushilbansal** [stripe/stripe-react-native#330]
I integrated stripe with my React Natve App. My question is: Is stripe allowed to collect payments for in app purchases? We are selling online consulting services.

In the screenshot below if the user selects credit/debit card option then Google pay will not recieve its cut. I am worried that this might cause ban on Google or Apple stores. Have you guys considered this issue? Apologies if this issue is not an issue - wanted to seek clarification rather than thinking and worrying about it. 

I spoke to someone on the support and he mentioned that there is no way to hide the second option (collecting debit/credit card info).
![WhatsApp Image 2021-06-10 at 16 28 59](https://user-images.githubusercontent.com/6096693/121563058-fa729480-ca11-11eb-871c-f395abf420a8.jpeg)

**Comment by thorsten-stripe** [comment]
If you're selling digital products or services within your app, (e.g. subscriptions, in-game currencies, game levels, access to premium content, or unlocking a full version), you must use the app store's in-app purchase APIs. See [Apple's](https://developer.apple.com/app-store/review/guidelines/#payments) and [Google's](https://support.google.com/googleplay/android-developer/answer/9858738?hl=en&ref_topic=9857752) guidelines for more information. For all other scenarios you can use this SDK to process payments via Stripe.

I've added a section to the README for this: https://github.com/stripe/stripe-react-native#recommended-usage

**Comment by Mihai-github** [comment]
Hi, I've got my app rejected by Apple because of the problem of not having in-app purchases. I checked the docs you've attached above but I am not sure what to do because no one says a clear way of achieving this in react native and that's a bit hard to know what to do because we did all the process with react-native stripe SDK and now we have to redo the process I guess but I would like to know for sure what to do...

Thank you :)
