### ISSUE TITLE
stripeErrorCode and declineCode empty for iOS on confirmPaymentMethod error

### ISSUE THREAD

**Issue by lucasfronza** [stripe/stripe-react-native#362]
**Describe the bug**
When calling `confirmPaymentMethod` with the card `4000 0082 6000 3178` (which is expected to fail with insufficient funds), both `stripeErrorCode` and `declineCode` are empty on iOS. On Android, as expected, both fields are present.

**To Reproduce**
1. On iOS, having set up a payment intent with a card that will fail, call
```ts
const { paymentIntent, error } = await confirmPaymentMethod(action.client_secret, {
      type: 'Card',
      paymentMethodId: (...paymentMethodId...),
})

console.log({ error })
```
2. Error object is
```ts
error: {
    code: "Failed",
    localizedMessage: "Your card has insufficient funds.",
    message: "There was an error confirming the Intent. Inspect the `paymentIntent.lastPaymentError` or `setupIntent.lastSetupError` property.",
    declineCode: null,
    type: null,
    stripeErrorCode: null,
}
```

**Expected behavior**
Android `error` object contains what I believe is the expected behavior:
```ts
error: {
    stripeErrorCode: "card_declined",
    declineCode: "insufficient_funds",
    localizedMessage: "Your card has insufficient funds.",
    message: "Your card has insufficient funds.",
    type: "card_error",
    code: "Failed",
}
```

**Comment by arekkubaczkowski** [comment]
@bg-stripe 
it seems that stripe-ios doesn't provide enough information in this specific case:
```
(lldb) po error?.userInfo
▿ Optional<Dictionary<String, Any>>
  ▿ some : 2 elements
    ▿ 0 : 2 elements
      - key : "NSLocalizedDescription"
      - value : "Your card has insufficient funds."
    ▿ 1 : 2 elements
      - key : "com.stripe.lib:ErrorMessageKey"
      - value : "There was an error confirming the Intent. Inspect the `paymentIntent.lastPaymentError` or `setupIntent.lastSetupError` property.
      
```
there are missing keys like `com.stripe.lib:DeclineCodeKey`, `com.stripe.lib:StripeErrorCodeKey`, `com.stripe.lib:StripeErrorTypeKey`

cc @thorsten-stripe

**Comment by LPGuidetti** [comment]
Yep I'm running into the exact same issue. I'm following the [SetupFuturePayment](https://stripe.com/docs/payments/save-and-reuse?platform=react-native#react-native-create-customer) documentation word for word but when I get around to testing the different cards and their failure types I'm consistently getting `"lastPaymentError": null`. This is a bummer because the whole recovery flow is based on the messages inside lastPaymentError. This makes the failure handling really ugly as I can't differentiate between authentication_required or insufficient_funds and forces me to post very unhelpful alerts. Example of one of the retrievedPaymentIntents:

`retrieved paymentIntent {"amount": 1500, "canceledAt": null, "captureMethod": "Automatic", "clientSecret": "pi_1JB76pHV8lPbMRVJmk58U679_secret_5I90pC9z3M78zVIoKwJtClDiu", "confirmationMethod": "Automatic", "created": "1625788703000.0", "currency": "eur", "description": "<Stripe.STPPaymentIntent: 0x60000305e490; stripeId = pi_1JB76pHV8lPbMRVJmk58U679; amount = 1500; canceledAt = nil; captureMethod = Optional(\"automatic\"); clientSecret = <redacted>; confirmationMethod = Optional(\"automatic\"); created = 2021-07-08 23:58:23 +0000; currency = eur; description = nil; lastPaymentError = nil; livemode = false; nextAction = Optional(<Stripe.STPIntentAction: 0x600001a96f80; type = use_stripe_sdk; useStripeSDK = <STPIntentActionUseStripeSDK: 0x600003d74e10; directoryServer = nil; directoryServerID = nil; directoryServerKeyID = nil; serverTransactionID = nil; directoryServerCertificate = nil; rootCertificateStrings = nil; threeDSSourceID = Optional(\"src_1JB76pHV8lPbMRVJlVvVABZk\"); type = Optional(three_d_secure_redirect); redirectURL = Optional(https://hooks.stripe.com/redirect/authenticate/src_1JB76pHV8lPbMRVJlVvVABZk?client_secret=src_client_secret_qu1nWQVU83fENnUN1fox4ov5&source_redirect_slug=test_YWNjdF8xSFI4cmFIVjhsUGJNUlZKLF9Kb2tjdDU4OFpmTHNrQlI0bzVJWUpwUGk3UlQ0TmtL0100G313XJEv)>>); paymentMethodId = Optional(\"pm_1JB6yaHV8lPbMRVJ46UvPgzz\"); paymentMethod = nil; paymentMethodTypes = Optional([\"card\"]); receiptEmail = nil; setupFutureUsage = Optional(\"on_session\"); shipping = nil; sourceId = nil; status = Optional(\"requires_action\")>", "id": "pi_1JB76pHV8lPbMRVJmk58U679", "lastPaymentError": null, "livemode": false, "paymentMethodId": "pm_1JB6yaHV8lPbMRVJ46UvPgzz", "receiptEmail": null, "shipping": null, "status": "RequiresAction"}`

**Comment by thorsten-stripe** [comment]
On iOS this information is not directly returned in the error object. You will need to call `retrievePaymentIntent` to access `lastPaymentError`.

**Comment by LPGuidetti** [comment]
@thorsten-stripe thanks for your help but that is exactly how I got the response I posted above. My code:
`const { error, paymentIntent } = await retrievePaymentIntent(clientSecret);
console.log('retrieved paymentIntent', paymentIntent)`

So I'm afraid something else must be happening.

**Comment by thorsten-stripe** [comment]
@LPGuidetti that's because the status of your PaymentIntent is `RequiresAction` so you simply need to call `handelCardAction` on it.

**Comment by LPGuidetti** [comment]
@thorsten-stripe ah interesting, I did not see any mention of that in the [SetupFuturePayment example](https://github.com/stripe/stripe-react-native/issues/362#:~:text=I%27m%20following%20the-,SetupFuturePayment,-documentation%20word%20for) or [documentation](https://stripe.com/docs/payments/save-and-reuse?platform=react-native#react-native-create-payment-intent-off-session). 

I have to admit I still don't fully comprehend why the documentation calls to build the whole recovery flow around the `lastPaymentError` field if that field may come back as `null`. For what its worth here's the code I have built:

If the paymentIntent's `status` comes back as `succeeded` I do nothing. Otherwise I do the following:

```
const billingDetails: PaymentMethodCreateParams.BillingDetails = {
    email: user?.email
  }; 

const { error } = await confirmPayment(
    result.data.clientSecret,
{
    type: 'Card',
    billingDetails,
    paymentMethodId: paymentMethodID,
}
);

if (error) {
    setIsLoading(false)
    errorWithPayment(error.message);
} else {
    setIsLoading(false)
    setSuccess(true) 
}
```

**Comment by thorsten-stripe** [comment]
My guess is that you're missing the `off_session:true` param, that's why your PI is in `RequiresAction` and therefore your flow deviates from the docs. 
![image](https://user-images.githubusercontent.com/23213994/125928116-b37142b0-ff32-472e-a118-b10e0b7ee46e.png)

**Comment by LPGuidetti** [comment]
@thorsten-stripe you are spot on! I didn’t know that that flag would affect the PI response. What is the correct flow to follow if you save a card for future use but the user will be on session when it is charged later on? Kind of like Uber or Lyft? Really appreciate all the help.

**Comment by thorsten-stripe** [comment]
@LPGuidetti in that case you call `handleCardAction` on the PaymentIntent if it is in `RequiresAction` state: https://stripe.com/docs/payments/accept-a-payment-synchronously?platform=react-native#react-native-handle-next-actions

**Comment by lucasfronza** [comment]
> What is the correct flow to follow if you save a card for future use but the user will be on session when it is charged later on? Kind of like Uber or Lyft? Really appreciate all the help.

Hey @LPGuidetti, just to clear some things out.. At the end of an Uber or Lyft ride, the user will be charged regardless if they have the app open or not, which means, it is an `off_session` payment.
User having your app open at the time of the charge doesn't mean an on-session payment. On-session would be something like a product purchase flow, in which the user is buying a product, and is making an active action to buy that.
Off-session means any payment capture that might occur in a later date (either 5 minutes, or a month later).
If your app has a similar case to Uber or Lyft, I think you might be looking for off_session payments.

**Comment by charliecruzan-stripe** [comment]
Closing as the correct flow is as stated above: On iOS this information is not directly returned in the error object. You will need to call `retrievePaymentIntent` to access `lastPaymentError`, as stated in the error message itself.
