### ISSUE TITLE
[Docs] tipsi-stripe migration guide

### ISSUE THREAD

**Issue by thorsten-stripe** [stripe/stripe-react-native#364]
It's come up a couple of times that folks migrating from tipsi-stripe are struggling a bit, especially when they are using class components and can't use hooks. We should provide some migration docs for them.

**Comment by richkuo** [comment]
Hi,

I just completed the migration - would love to help contribute.
Are there some sample migration docs to help get started?
Thanks!

**Comment by bramski** [comment]
@russmenum What are the roadblocks with google pay?

**Comment by russmenum** [comment]
@bramski it is resolved now, there were some cumbersome tests to do with the lack of prod access while getting to the request access point. In the end, turned out to be TEST Vs NOT TEST MODE for Stripe. Which in that particular app is a little cumbersome to switch between. Google also is not exactly being RN friendly with the required brand assets. It kind of screwed up our order/check-out flow. But got it all done. Long-term do want to migrate to the "official" Stripe library.

**Comment by juanma16062001** [comment]
Hey there! I'm about to start migrating if everything goes fine and @richkuo hasn't already wrote the guide, i will be happy to contribute.

**Comment by thorsten-stripe** [comment]
Thanks everyone for offering your help. Would appreciate if you could look at https://github.com/stripe/stripe-react-native/pull/512 and let us know if it looks good. Thanks 🙏
