### ISSUE TITLE
ApplePay: Confirm payment on the server

### ISSUE THREAD

**Issue by TommasoTate** [stripe/stripe-react-native#488]
Our implementation needs to tokenize ApplePay and GooglePay payment methods in order to process the payment server side.

As recently added for `useGooglePay` (https://github.com/stripe/stripe-react-native/pull/441), I wonder if there's already a timeline for adding a `createApplePayPaymentMethod` function to `useApplePay` hook.
If not, I would ask if there's any workaround we can follow in order to temporarily emulate this feature.

**Comment by thorsten-stripe** [comment]
@TommasoTate Apple Pay automatically returns the payment method when `presentApplePay` resolves: https://stripe.dev/stripe-react-native/api-reference/modules.html#ApplePayResult 

You can then send the payment method to your server and charge it there. Afterward you will need to return the `client_secret` of your PaymentIntent to your client and call `confirmApplePayPayment` with it in order to close the Apple Pay sheet.
