### ISSUE TITLE
Create token BankAccount with params

### ISSUE THREAD

**Issue by marquina-abreu** [stripe/stripe-react-native#575]
**Is your feature request related to a problem? Please describe.**
When will it be possible to create a bankAccount token in the library? I was investigating and I found absolutely nothing .. I wish there was something similar to how tipsi-stripe has it

`const bankAccount = await stripe.createTokenWithBankAccount(dataParams);`

**Comment by ReidPolis1** [comment]
I too wish this was a feature

**Comment by BogdanVV** [comment]
Well, seems like it's not supported yet :(
When I'm trying to use createToken({ type: 'BankAccount' }) (according to [api doc](https://stripe.dev/stripe-react-native/api-reference/interfaces/Card.CreateTokenParams.html) I'm getting an error object with the message 'BankAccount type is not supported yet'.
That's quite frustrating because I'll have to pick another library for my app after I've already implemented some features using stripe-react-native.
Also, I'd appreciate some response from the creators.

**Comment by BogdanVV** [comment]
The [PR ](https://github.com/stripe/stripe-react-native/pull/591) is pending for 2.5 months :(
