### ISSUE TITLE
Google Pay/Apple pay using CardField instead of PaymentSheet

### ISSUE THREAD

**Issue by Gabotron-ES** [stripe/stripe-react-native#617]
Hi everybody, currently I can't seem to find how to use Google Pay or Apple Pay with CardField component, is it currently possible?

**Comment by anija** [comment]
Hi, if you mean to avoid to use the Stripe Payment Sheet, then I've succesfully implemented Apple Pay and Google Pay with the CreatePaymentMethod flux in these days (with the latest version of the library). I don't use CardField component since both methods use native dialogues.

**Apple Pay**
use the hook:
`const { presentApplePay, isApplePaySupported, confirmApplePayPayment } = useApplePay();`

Then use isApplePaySupported to know if it's supported in order to enable/disable it.
Then i use 
```
const pm = await presentApplePay({
    cartItems: nativePaymentParams.items,
    country: 'IT',
    currency: cart.currency,
    shippingMethods: [],
    requiredShippingAddressFields: [],
    requiredBillingContactFields: [],
});
```
To obtain the Payment Method ID and proceed like with a normal Card on backend side.
After the payment intent has been requested to stripe by the backend, returning the client secret to me, i do:
`await confirmApplePayPayment(clientSecret);`
This will close the Apple Pay native dialogue.

**Google Pay**
Since i can't find any isGooglePaySupported, i do this:
```
const { error } = await initGooglePay({
  merchantName: config.merchantName,
  countryCode: config.merchantCountryCode,
  testEnv: version.environment !== 'prod',
});
```
Assuming that if there's an error, it means that Google Pay is not supported (but i still have to test this).
Then:
`const pm = await createGooglePayPaymentMethod(nativePaymentParams.googlePay);`
And proceed as always on backend side. No needs to close or confirm the payment as Apple Pay requires, as it can be confirmed directly on backend.

Hope this helps ;)

**Comment by Gabotron-ES** [comment]
Hi my friend, I will take a look at your code, looks very nice I must say!

**Comment by arekkubaczkowski** [comment]
@Gabotron-ES answering to your question
> Hi everybody, currently I can't seem to find how to use Google Pay or Apple Pay with CardField component, is it currently possible?

No it's not possible, CardField/CardForm components are dedicated to processing classic card payments and not related to any wallets.

However, considering such solution you must be aware that collecting the data on client side has to meet [PCI Compilance](https://stripe.com/docs/security/guide#validating-pci-compliance) requirements and it's not recommended without any experience within this area.

**Comment by rockstarrabbitri** [comment]
> Hey @arekkubaczkowski, thanks for the response but unfortunately I have tried both with and without the android SDK in my app `build.gradle` and get the same error. I didn't have it at first but saw it in the docs [here](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet#react-native-google-pay) (under the `Optional Enable Google Pay` dropdown) so ended up adding it
> 
> UPDATE: We managed to solve our issue. It was a local config problem where we had forced versions of certain packages (for reasons that only our long gone developers know) that were causing conflicts. We removed this and stopped seeing the error

Your comment helped me a lot! Thanks a lot!
Previous developers decided to write fixed versions of packages for some reason, as well.😂

I just removed this code from build.gradle:

`configurations.all {
        resolutionStrategy {
            force 'com.google.android.gms:play-services-gcm:16.1.0'
            force 'com.google.android.gms:play-services-base:16.1.0'
            force 'com.google.firebase:firebase-core:16.0.9'
            force 'com.google.firebase:firebase-messaging:18.0.0'
        }
}`
