### ISSUE TITLE
Undefined symbol: --- getting 5 errors

### ISSUE THREAD

**Issue by kmamtora** [stripe/stripe-react-native#627]
**I am getting 5 errors **

**To Reproduce**
1. created new project
2. added new stripe react native from here https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet-custom
3. See error

![image](https://user-images.githubusercontent.com/44718980/136282158-468df98a-bc9d-43da-a4af-9b7da56f4cc8.png)

 - Version "react-native": "0.65.0",

**Comment by co2nut** [comment]
> @kmamtora please follow troubleshooting section https://github.com/stripe/stripe-react-native#troubleshooting

I'm getting more errors after removing 

$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)

kindly advice, thanks

**Comment by co2nut** [comment]
for those who are facing the same issue, can try out the solution below:

![image](https://user-images.githubusercontent.com/4594000/147618945-2945e95a-3c01-4125-87bd-9487df5f55ca.png)

added "$(SDKROOT)/usr/lib/swift" instead of removing $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) & $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
