### ISSUE TITLE
[How to] Subscription with Apple Pay

### ISSUE THREAD

**Issue by takeerdevs** [stripe/stripe-react-native#639]
Hello everyone, i'm having a trouble creating subscription with apple pay, according to stripe docs https://stripe.com/docs/apple-pay?platform=react-native#recurring-payments

> ### Recurring payments
> You can use Apple Pay tokens to create one-off payments or subscriptions. For repeat purchases that aren’t related to a subscription, Stripe recommends that you create single-use tokens. Your customer must authenticate with the Apple Pay payment sheet each time -attempting to reuse payment information for a non-subscription payment can result in it being declined.
> 

and in this https://support.stripe.com/questions/using-apple-pay-for-recurring-payments
> ### Using Apple Pay for recurring payments
> Apple Pay will create a card token that you can use to create a Customer object within Stripe. You can use that token to create a recurring payment or subscription for a Customer using Billing.

I haven't seen any existing example that shows how to get apple pay card token with this lib [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) so i can proceed creating subscription with apple pay
Does anyone know how to do this, Thanks.

**Comment by dqii** [comment]
Did you end up figuring this out?

**Comment by cormacncheese** [comment]
Also wondering how to implement this

**Comment by cormacncheese** [comment]
Ended up using expo-in-app-purchases because Apple Pay and In-App-Purchases are two different things.  Apple handles subscriptions on their end when using In-App-Purchases.

But for those still working to implement Stripe / Apple Pay I found these links helpful:
https://stripe.com/docs/apple-pay
https://support.stripe.com/questions/using-apple-pay-for-recurring-payments
https://stackoverflow.com/questions/66138846/stripe-use-apple-pay-on-the-web-for-a-subscription

**Comment by kvacke** [comment]
@takeerdevs Did you end up finding an example on how to implement the subscription?
