### ISSUE TITLE
[Android] createCardPaymentSetupParams endpoint does not support token cards.

### ISSUE THREAD

**Issue by jamesblasco** [stripe/stripe-react-native#643]
While creating a confirmation payment param object. For Intents params, it is possible to use token cards, for setupParams it is only allowed to use the card data from the cardField/cardFormField

https://github.com/stripe/stripe-react-native/blob/a0d52490689b8fab58707551f5c22c37cac82442/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt#L93-L101

vs 

https://github.com/stripe/stripe-react-native/blob/a0d52490689b8fab58707551f5c22c37cac82442/android/src/main/java/com/reactnativestripesdk/PaymentMethodCreateParamsFactory.kt#L166-L175

**Comment by SimonErich** [comment]
Sorry, don't intend to stress, but is there any eta for this. We are currently waiting with an app release, because this feature is missing. Would be awesome to be able to plan.

**Comment by atearjen** [comment]
any update?

**Comment by Avejack** [comment]
We really need this update... Or is there a workaround?

**Comment by daveols** [comment]
Is there any technical reason as to why a fix for this hasn't been done yet? We're blocked implementing subscriptions via Google Pay due to this issue and are considering opening a PR to resolve it as on the surface it looks pretty trivial (assuming Stripe supports SetupIntents via tokenised card and it's simply a matter of modifying the above function).

@jamesblasco @acomley-stripe @charliecruzan-stripe if one of you can confirm the above for me I'll have a go at it tomorrow.

**Comment by charliecruzan-stripe** [comment]
Hi! thanks for the ping on this, I can open a PR for this today

**Comment by charliecruzan-stripe** [comment]
PR here- https://github.com/stripe/stripe-react-native/pull/931
