### ISSUE TITLE
[Apple Pay] presentApplePay() and timeout

### ISSUE THREAD

**Issue by anija** [stripe/stripe-react-native#684]
Hi,

I've succesfully implemented Apple Pay with this flux:
1. presentApplePay to obtain paymentMethod
2. server side call using the paymentMethod to obtain the clientSecret
3. confirmApplePayPayment using the clientSecret

I've just one problem.
If the server side call tooks too long, the applePay sheet close itself saying the app hasn't be able to complete the payment.
I can't find any hint in documentation on how long is this timeout or (better) how to catch the sheet closing for timeout on frontend side (in order to cancel the request and don't proceed further and mark the payment as canceled for the user).

Any idea? Thank you.

**Comment by anija** [comment]
In addition to this:

If i try to do:
`const { error } = await confirmApplePayPayment(clientSecret);`
After the timeout message has been received and the applePay sheet has been closed, the promise is never resolved.

**Comment by ClementLevesque** [comment]
Hello,

I also have a problem with the confirmApplePayPayment method which never resolve.

Here is what I do :

- I execute presentApplePay method => Apple pay interface is properly displayed
- The payment is processed in the backend (payment intent creation)
- I click outside the apple pay payment interface before the process ends what closes the interface
- The method confirmApplePayPayment then never resolves nor timeouts

```javascript
const { error, paymentMethod } = await presentApplePay({...});
try {
    const stripeSecret = await processPaymentInBackend(...);
    const { error } = await confirmApplePayPayment(clientSecret);     // Never resolves if the apple pay interface is closed
catch(e) {...}
```
Expected behavior: 
- either : the confirmApplePayPayment throws a canceled error
- or : the confirmApplePayPayment  throws a timeout error

Any idea ? Thanks 🙏
