### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by sunset1234321** [stripe/stripe-react-native#742]
For debug build on ios, works fine.

For release build on ios, 
`React/RCTBridgeDelegate.h` not found. 

any ideas?

**Comment by NamNP06** [comment]
hello. You can try : cd ios: pod update

**Comment by charliecruzan-stripe** [comment]
To help troubleshoot issues, we need reproducible demo (like a linked Github repo). Otherwise, your best bet is to follow the Readme and try setting `stripe-react-native` up in a fresh new project. If you google search that error, you can find some helpful SO posts: https://www.google.com/search?q=react%2FRCTBridgeDelegate.h&oq=react%2FRCTBridgeDelegate.h&aqs=chrome..69i57j0i512j69i58.539j0j7&sourceid=chrome&ie=UTF-8
