### ISSUE TITLE
initGooglePay have the same init error that INIT_PAYMENTSHEET had

### ISSUE THREAD

**Issue by carl0shd** [stripe/stripe-react-native#844]
**Describe the bug**
Hi Guys, I have multiple errors (+80 daily) in my production app using Stripe, when I call `initGooglePay` at the launch in my app, I have this error:

`java.lang.NullPointerException: null cannot be cast to non-null type androidx.appcompat.app.AppCompatActivity`

I think is the same error that the `INIT_PAYMENTSHEET` have in old versions: https://github.com/stripe/stripe-react-native/pull/783

This is the full log:

<img width="859" alt="image" src="https://user-images.githubusercontent.com/8359234/158400986-416a720f-cfa1-4624-b3d6-cbc6cb21dc91.png">

apparently, the error doesn't always occur, it seems to be random.

**To Reproduce**
N/A, I don't have instructions to reproduce this :(

**Expected behavior**
Not have this crash.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Stripe RN version: 0.2.4
RN Version: 0.66

**Comment by carl0shd** [comment]
Hi @charliecruzan-stripe, actually the app uses version 0.2.4

**Comment by charliecruzan-stripe** [comment]
thanks :) fix incoming, it's extremely helpful that you included the crash logs in your issue report 👏

**Comment by goguda** [comment]
![Screenshot_20220408_143750](https://user-images.githubusercontent.com/26887502/162501761-4a17c156-68ae-4c98-9566-c686cf16e3f0.png)

Same issue seems to occur at line 244 in StripeSdkModule.kt as well... null check needed here too?

I find it strange because based on visit logs I believe this is occurring without the user even interacting with any Stripe APIs yet, other than StripeProvider wrapping the root of the app.

Looking at line 244 of StripeSdkModule.kt...

`(currentActivity as AppCompatActivity).supportFragmentManager.beginTransaction().add(paymentLauncherFragment, "payment_launcher_fragment").commit()`

Taking a quick look at the internals of the library, my concern is, is a null check enough, or are null checks really just masking another problem? Should currentActivity ever actually be null in this case if the RN app has to be open for any of these API calls to even occur (as far as I know)?

It also doesn't seem to be happening to every user, but I am having a few Android users per day trigger this error on my side in production. I cannot seem to reproduce it myself, sadly. It seems to happen across a wide range of Android devices. All my errors have interestingly happened on Android 10 or Android 11:

![image](https://user-images.githubusercontent.com/26887502/162511710-e0dad4fe-e585-445a-9962-5468ee21a29a.png)
![image](https://user-images.githubusercontent.com/26887502/162511754-7a9cec19-7f9c-43a9-a8bb-2bd16e324a06.png)
![image](https://user-images.githubusercontent.com/26887502/162511924-aa76646b-936f-47ed-89f0-41477d3a6c97.png)
![image](https://user-images.githubusercontent.com/26887502/162512062-27c1b8e6-3411-4315-8a28-5168b4871719.png)
![image](https://user-images.githubusercontent.com/26887502/162512230-39ee004b-3bd7-47e0-a713-d2fa80ae4682.png)
![image](https://user-images.githubusercontent.com/26887502/162512419-034659b9-5614-48e7-8788-2be5e1e5643e.png)
![image](https://user-images.githubusercontent.com/26887502/162512846-a7654a47-2ad9-48ea-a407-0694aea76525.png)
![image](https://user-images.githubusercontent.com/26887502/162512992-5a09a257-c0be-498b-a672-13a4a4f055a0.png)

Wish I could get some more info on exactly what is causing it, but this is all I've got.

I'm using stripe-react-native v. 0.6.0, but it was happening in older versions as well.
