### ISSUE TITLE
Completely customized form

### ISSUE THREAD

**Issue by december1990** [stripe/stripe-react-native#988]
I followed the instructions on stripe website to customize the primary colors, borders, etc. But they didn't affect the look and feel of payment sheet.

I need to implement a completely customized payment sheet, is it possible using this sdk or is it even possible in react native to do so ? Maybe by talking straight to stripe api or something.

**Comment by charliecruzan-stripe** [comment]
> But they didn't affect the look and feel of payment sheet.

Hm, what do you mean? If the customization options didn't result in any UI changes, then something's going wrong (please let me know how to reproduce that in a new bug report with all the details we ask for)

Otherwise, if you want a totally custom UI then yeah, you'd need to create it using the individual components (like CardField or CardForm), and functions (like `confirmPayment`)

**Comment by charliecruzan-stripe** [comment]
Closing this for now. If this is a bug with the `appearance` field on `initPaymentSheet`, please provide a repro

**Comment by december1990** [comment]
to support IOS 11, I have installed the version 0.5 and seems that this capability has been added in version 0.11
